# Generated by Django 4.2.7 on 2026-01-22 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('content', models.TextField(help_text='Markdown content')),
                ('note_type', models.CharField(choices=[('note', 'Note'), ('task', 'Task'), ('project', 'Project')], db_index=True, default='note', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('color', models.CharField(default='#808080', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_tag_name')],
            },
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('reference', 'Reference'), ('parent', 'Parent'), ('child', 'Child'), ('related', 'Related')], db_index=True, default='reference', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='notes.note')),
                ('target_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='notes.note')),
            ],
            options={
                'verbose_name': 'Note Link',
                'verbose_name_plural': 'Note Links',
                'db_table': 'note_links',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='linked_notes',
            field=models.ManyToManyField(blank=True, related_name='backlinks', through='notes.NoteLink', to='notes.note'),
        ),
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='notes.tag'),
        ),
        migrations.CreateModel(
            name='TaskMeta',
            fields=[
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task_meta', serialize=False, to='notes.note')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='todo', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Task Metadata',
                'verbose_name_plural': 'Task Metadata',
                'db_table': 'task_meta',
                'indexes': [models.Index(fields=['status', 'priority'], name='idx_status_priority'), models.Index(fields=['due_date', 'status'], name='idx_due_status'), models.Index(fields=['priority', 'due_date'], name='idx_priority_due')],
            },
        ),
        migrations.AddIndex(
            model_name='notelink',
            index=models.Index(fields=['source_note', 'link_type'], name='idx_source_link_type'),
        ),
        migrations.AddIndex(
            model_name='notelink',
            index=models.Index(fields=['target_note', 'link_type'], name='idx_target_link_type'),
        ),
        migrations.AddIndex(
            model_name='notelink',
            index=models.Index(fields=['source_note', 'target_note'], name='idx_source_target'),
        ),
        migrations.AlterUniqueTogether(
            name='notelink',
            unique_together={('source_note', 'target_note', 'link_type')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'note_type'], name='idx_owner_type'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'created_at'], name='idx_owner_created'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'updated_at'], name='idx_owner_updated'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['note_type', 'created_at'], name='idx_type_created'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_archived', 'is_deleted'], name='idx_archived_deleted'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'is_deleted', 'is_archived'], name='idx_owner_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='idx_telegram_id'),
        ),
    ]
